global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "payment-scheduler-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "payment-scheduler-executor"
    static_configs:
      - targets: ["executor:8001"]
    metrics_path: /metrics
